### ISSUE TITLE
Missing args.json

### ISSUE THREAD

**Issue by zjp-shadow** [Kebii/TapMo#3]
```
python3 -m sample.generate_handle_motion --model_path ../weights/diffusion_model_latest.pt --arch trans_dec --emb_trans_dec False --dataset t6d_mixrig --char_feature_path ../demo/shape_features/001.npy --save_path ../demo/motion/motion_3 --text_prompt "walk forward and turn right."
Loading model args from [../weights/args.json]
Traceback (most recent call last):
  File "/home/zjp/anaconda3/envs/sfpt/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/zjp/anaconda3/envs/sfpt/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/zjp/TapMo/shape_diffusion/sample/generate_handle_motion.py", line 205, in <module>
    main()
  File "/home/zjp/TapMo/shape_diffusion/sample/generate_handle_motion.py", line 19, in main
    args = generate_args()
  File "/home/zjp/TapMo/shape_diffusion/utils/parser_util_tapmo.py", line 226, in generate_args
    return parse_and_load_from_model(parser)
  File "/home/zjp/TapMo/shape_diffusion/utils/parser_util_tapmo.py", line 22, in parse_and_load_from_model
    assert os.path.exists(args_path), 'Arguments json file was not found!'
AssertionError: Arguments json file was not found!
```
Thanks for sharing the inference code!
I download the `weights.zip` from google drive and unzip it into the folder but missing `args.json` file to get the arguments, could you provide it?

**Comment by zjp-shadow** [comment]
the wrong path, I found it, sorry
